POST http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2MjM3MjQ0LCJ1c2VySWQiOjF9.RgDyBuZxHxdpfZo-z5Z1hgLHaZkw-dmXPY0N86k-NyM